# BorgBackup ssh server Dockerfile
#
# We require the following bind mounts at runtime:
# Path                                Purpose
# ---------------------------------   ----------------------------------------
# /repos                              borgbackup repositories
# /etc/ssh/ssh_host_ed25519_key       ED25519 private host key (not stored in image)
# /etc/ssh/ssh_host_ed25519_key.pub   ED25519 public host key (not stored in image)
# /home/borg/.ssh/authorized_keys     ssh authorized_keys (not stored in image)
#
#
# UFW Rules
# allow all loopback traffic; it is not possible for packets from other
# interfaces to cross over to the loopback interface
# sudo ufw allow in on lo
# allow incoming ssh from known hosts
# sudo ufw allow in on enp4s0 log proto tcp from <host> to <self> port 2222 comment 'SSH'
# sudo ufw default deny incoming
# sudo ufw default allow outgoing
# ---- cut here ----
#
# Cautions when using UFW:
# Docker provides a DOCKER-USER iptables chain.
# UFW and iptables are mutually exclusive firewall tools.
# Without persistent iptables rules, we use the UFW 'before' hook
# in /etc/ufw/before.rules:
# ---- cut here ----
# *filter
# ...
# :DOCKER-USER - [0:0]
# ...
# -A DOCKER-USER -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
# -A DOCKER-USER -i br+ -o br+ -j ACCEPT
# -A DOCKER-USER -d 172.16.0.0/12 -j ACCEPT
# -A DOCKER-USER -j DROP
# ...
# COMMIT
# ---- cut here ----
# Without the above additions, docker traffic will be blocked by the default
# UFW incoming deny policy.

# Debian release codename; see https://www.debian.org/releases/
ARG DEBIAN_CODENAME=bookworm

FROM debian:${DEBIAN_CODENAME}

# borgbackup pip package version spec; see https://pypi.org/project/borgbackup/
ARG BORGBACKUP_VERSION=1.4.3

# Install OpenSSH server, pipx, and build dependencies for BorgBackup
# Package            Why
# ---------------    ----------------------------------------
# openssh-server     Provides sshd
# pipx               Install and execute apps from Python packages;
#                    allows us to use specific borgbackup versions,
#                    rather than being limited to the version supplied
#                    with the base debian:bookworm image.
# pkg-config         Finds compiler flags for libraries
# build-essential    GCC, make, and other build tools
# libssl-dev         OpenSSL development headers (encryption)
# libacl1-dev        ACL support for file permissions
# libfuse-dev        FUSE support for borgfs mounting
# liblz4-dev         LZ4 compression library
# libzstd-dev        Zstandard compression library
# libxxhash-dev      xxHash hashing library
# python3-dev        Python development headers for C extensions

# Additional (non-essential) packages:
# Package            Why
# ---------------    ----------------------------------------------------
# iproute2           Provides ss utility to investigate sockets for debug

RUN apt-get update && \
    apt-get install -y \
    openssh-server \
    pipx \
    pkg-config \
    build-essential \
    libssl-dev \
    libacl1-dev \
    libfuse-dev \
    liblz4-dev \
    libzstd-dev \
    libxxhash-dev \
    python3-dev \
    iproute2 \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Remove ssh host keys generated by openssh-server package install;
# we require the user to bind mount /etc/ssh/ssh_host_ed25519_key and /etc/ssh/ssh_host_ed25519_key.pub
RUN rm /etc/ssh/ssh_host_*_key*

# Create sshd runtime directory
RUN mkdir /run/sshd

# Create borg user and borg group; per the debian policy manual, these will be 1000 and 1000, respectively
# https://www.debian.org/doc/debian-policy/ch-opersys.html#users-and-groups
RUN adduser --home /home/borg --disabled-password --comment "borgbackup" borg

# Create borg user's .ssh directory and placeholder authorized_keys for the bind mount
RUN mkdir /home/borg/.ssh && \
    touch /home/borg/.ssh/authorized_keys && \
    chown -R borg:borg /home/borg/.ssh && \
    chmod -R 700 /home/borg/.ssh

# Make root directory for borg repositories and make it owned by borg
RUN mkdir /repos && \
    chown borg:borg /repos

# Install BorgBackup via pipx as borg user
RUN su - borg -c "/usr/bin/pipx install borgbackup==${BORGBACKUP_VERSION}"

# Remove build dependencies (keep runtime libraries)
RUN apt-get remove -y \
    pkg-config \
    build-essential \
    python3-dev \
    && apt-get autoremove -y \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Configure SSHD for container environment (in-place modifications)
# Per https://borgbackup.readthedocs.io/en/stable/usage/serve.html:
#
# Setting               Value   Purpose
# ClientAliveInterval   10      Send keepalive message every 10 seconds
# ClientAliveCountMax   30      Disconnect after 30 missed keepalives
#
# Total timeout: 10 seconds × 30 = 300 seconds (5 minutes)
#
# Why this matters for BorgBackup:
# - Keeps SSH connection alive during long backup operations
# - Prevents firewall/NAT from closing idle connections
# - Allows backups to complete without interruption
# - Sends keepalive packets every 10 seconds
# - Disconnects only after 5 minutes of no response
RUN sed -i 's@#\?session\s*required\s*pam_loginuid.so@#session optional pam_loginuid.so@g' /etc/pam.d/sshd && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config && \
    sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config && \
    sed -i 's/#LogLevel[[:space:]]\+[[:alnum:]_]\+/Loglevel VERBOSE/' /etc/ssh/sshd_config && \
    sed -i 's/#ClientAliveInterval[[:space:]]\+[0-9]\+/ClientAliveInterval 10/' /etc/ssh/sshd_config && \
    sed -i 's/#ClientAliveCountMax[[:space:]]\+[0-9]\+/ClientAliveCountMax 30/' /etc/ssh/sshd_config && \
    sed -i 's/#\?AddressFamily.*/AddressFamily inet/' /etc/ssh/sshd_config && \
    sed -i '$ a AllowUsers borg' /etc/ssh/sshd_config && \
    sed -i 's|^#\?\s*HostKey\s\+/etc/ssh/ssh_host_ed25519_key|HostKey /etc/ssh/ssh_host_ed25519_key|' /etc/ssh/sshd_config


# Document that this container provides an SSH service on port 22.
# EXPOSE does not publish the port; it records intent so runtime tooling
# (e.g., `docker run -p` or Docker Compose) knows which port to map.
EXPOSE 22

# scripts/entrypoint.sh sets the borg account UID and GID to match those of
# the bind mapped /home/borg/.ssh/authorized_keys at container startup time
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod 0755 /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
